name: appclientes
description: A delivery flutter app

publish_to: "none"

version: 1.0.1+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  responsive_screen: ^1.0.0
  cupertino_icons: ^0.1.3
  permission_handler: ^5.0.1+1
  # flare_flutter: ^2.0.1
  shared_preferences: ^0.5.6
  intl: ^0.16.1
  geolocator: ^6.1.14
  geocoder: ^0.2.1
  location: ^3.2.4
  google_maps_flutter: ^1.2.0
  rxdart: ^0.24.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.4
  dio: ^3.0.9
  connectivity: ^2.0.2
  sentry: ^3.0.1
  url_launcher: ^5.4.2
  cached_network_image: ^2.5.0
  # decimal: ^0.3.5
  sign_in_with_apple: ^2.5.4
  tuple: ^1.0.3
  encrypt: ^4.0.0
  flutter_webview_plugin: ^0.3.11
  device_info: ^0.4.2+6
  package_info: ^0.4.3+4
  pattern_formatter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/gif/

  fonts:
    - family: Assistant-Bold
      fonts:
        - asset: assets/fonts/Assistant-Bold.ttf
    - family: Assistant-Light
      fonts:
        - asset: assets/fonts/Assistant-Light.ttf
    - family: Assistant-Regular
      fonts:
        - asset: assets/fonts/Assistant-Regular.ttf
